clearlag:
  remove_entities:
    - DROPPED_ITEMS # just these values will work
    - MONSTERS
    - PROJECTILES
    - EXPERIENCE_ORBS

  message: "<bold><green>Removed <color:#FF7B00>{count}</color:#FF7B00> entities!</green></bold>"
